-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.candidate_academies
(
    id integer NOT NULL,
    department_name character varying(255) NOT NULL,
    finished_year date,
    school_name character varying(255) NOT NULL,
    started_year date NOT NULL,
    candidate_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidate_languages
(
    id integer NOT NULL,
    language_level smallint NOT NULL,
    candidate_id integer NOT NULL,
    language_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidate_links
(
    id integer NOT NULL,
    link character varying(255) NOT NULL,
    candidate_id integer,
    link_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidate_technologies
(
    id integer NOT NULL,
    technology_name character varying(255) NOT NULL,
    candidate_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.candidates
(
    birth_date date,
    first_name character varying(255),
    last_name character varying(255),
    nationality_id character varying(255),
    id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.canidate_images
(
    id integer NOT NULL,
    candidate_id integer,
    image character varying,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL,
    city_name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    company_name character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    web_site character varying(255) NOT NULL,
    id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers_activation_by_system_users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id integer NOT NULL,
    system_user_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    created_date time with time zone NOT NULL,
    updated_date time with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL,
    created_date timestamp without time zone NOT NULL,
    deadline date NOT NULL,
    description character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    max_salary double precision NOT NULL,
    min_salary double precision NOT NULL,
    quota integer NOT NULL,
    city_id integer,
    employer_id integer,
    job_id integer,
    wayof_working_id integer,
    work_type_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobs
(
    id integer NOT NULL,
    "position" character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.languages
(
    id integer NOT NULL,
    language_name character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.link_types
(
    id integer NOT NULL,
    link_type character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_users
(
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.wayof_working
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    way_of_working character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.work_experiences
(
    id integer NOT NULL,
    finished_year date,
    "position" character varying(255) NOT NULL,
    started_year date NOT NULL,
    workplace_name character varying(255) NOT NULL,
    candidate_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.work_type
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    work_type character varying NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.candidate_academies
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.candidate_languages
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.candidate_languages
    ADD FOREIGN KEY (language_id)
    REFERENCES public.languages (id)
    NOT VALID;


ALTER TABLE public.candidate_links
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.candidate_links
    ADD FOREIGN KEY (link_id)
    REFERENCES public.link_types (id)
    NOT VALID;


ALTER TABLE public.candidate_technologies
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.canidate_images
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers_activation_by_system_users
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.employers_activation_by_system_users
    ADD FOREIGN KEY (system_user_id)
    REFERENCES public.system_users (id)
    NOT VALID;


ALTER TABLE public.job_positions
    ADD FOREIGN KEY (job_id)
    REFERENCES public.jobs (id)
    NOT VALID;


ALTER TABLE public.job_positions
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_positions
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.job_positions
    ADD FOREIGN KEY (wayof_working_id)
    REFERENCES public.wayof_working (id)
    NOT VALID;


ALTER TABLE public.job_positions
    ADD FOREIGN KEY (work_type_id)
    REFERENCES public.work_type (id)
    NOT VALID;


ALTER TABLE public.system_users
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.work_experiences
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id)
    NOT VALID;

END;
